CREATE USER sd IDENTIFIED BY sd;
 

GRANT "CONNECT" TO sd;
GRANT "RESOURCE" TO sd;
GRANT UNLIMITED TABLESPACE TO sd;
GRANT ALTER ANY CLUSTER TO sd;
GRANT ALTER SESSION TO sd;
GRANT CREATE PROCEDURE TO sd;
GRANT CREATE SEQUENCE TO sd;
GRANT CREATE TABLE TO sd;
GRANT CREATE TRIGGER TO sd;
GRANT CREATE VIEW TO sd;
ALTER USER sd DEFAULT ROLE ALL;
 
COMMIT;
