CREATE USER bd IDENTIFIED BY bd;

GRANT "CONNECT" TO bd;
GRANT "RESOURCE" TO bd;
GRANT UNLIMITED TABLESPACE TO bd;
GRANT ALTER ANY CLUSTER TO bd;
GRANT ALTER SESSION TO bd;
GRANT CREATE PROCEDURE TO bd;
GRANT CREATE SEQUENCE TO bd;
GRANT CREATE TABLE TO bd;
GRANT CREATE TRIGGER TO bd;
GRANT CREATE VIEW TO bd;
ALTER USER bd DEFAULT ROLE ALL;

COMMIT;
